/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: UC San Diego - Digital Media Lab (https://sketchfab.com/dml-ucsdlibrary)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ocean-wave-sim-0e5033a2469e499d875f3a75ba54ae9b
Title: Ocean Wave Sim
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Ocean(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/ocean_wave_sim.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="sketchfabtimeframe">
            <group name="Object_2" scale={0}>
              <group name="frame_249">
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_5" scale={0}>
              <group name="frame_248">
                <mesh
                  name="Object_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_8" scale={0}>
              <group name="frame_247">
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_11" scale={0}>
              <group name="frame_246">
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_14" scale={0}>
              <group name="frame_245">
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_17" scale={0}>
              <group name="frame_244">
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_20" scale={0}>
              <group name="frame_243">
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_23" scale={0}>
              <group name="frame_242">
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_26" scale={0}>
              <group name="frame_241">
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_29" scale={0}>
              <group name="frame_240">
                <mesh
                  name="Object_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_32" scale={0}>
              <group name="frame_239">
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_35" scale={0}>
              <group name="frame_238">
                <mesh
                  name="Object_37"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_37.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_38" scale={0}>
              <group name="frame_237">
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_41" scale={0}>
              <group name="frame_236">
                <mesh
                  name="Object_43"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_44" scale={0}>
              <group name="frame_235">
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_47" scale={0}>
              <group name="frame_234">
                <mesh
                  name="Object_49"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_50" scale={0}>
              <group name="frame_233">
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_53" scale={0}>
              <group name="frame_232">
                <mesh
                  name="Object_55"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_55.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_56" scale={0}>
              <group name="frame_231">
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_59" scale={0}>
              <group name="frame_230">
                <mesh
                  name="Object_61"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_61.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_62" scale={0}>
              <group name="frame_229">
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_65" scale={0}>
              <group name="frame_228">
                <mesh
                  name="Object_67"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_67.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_68" scale={0}>
              <group name="frame_227">
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_71" scale={0}>
              <group name="frame_226">
                <mesh
                  name="Object_73"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_73.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_74" scale={0}>
              <group name="frame_225">
                <mesh
                  name="Object_76"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_77" scale={0}>
              <group name="frame_224">
                <mesh
                  name="Object_79"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_79.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_80" scale={0}>
              <group name="frame_223">
                <mesh
                  name="Object_82"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_83" scale={0}>
              <group name="frame_222">
                <mesh
                  name="Object_85"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_85.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_86" scale={0}>
              <group name="frame_221">
                <mesh
                  name="Object_88"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_88.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_89" scale={0}>
              <group name="frame_220">
                <mesh
                  name="Object_91"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_91.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_92" scale={0}>
              <group name="frame_219">
                <mesh
                  name="Object_94"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_95" scale={0}>
              <group name="frame_218">
                <mesh
                  name="Object_97"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_97.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_98" scale={0}>
              <group name="frame_217">
                <mesh
                  name="Object_100"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_101" scale={0}>
              <group name="frame_216">
                <mesh
                  name="Object_103"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_103.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_104" scale={0}>
              <group name="frame_215">
                <mesh
                  name="Object_106"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_107" scale={0}>
              <group name="frame_214">
                <mesh
                  name="Object_109"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_109.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_110" scale={0}>
              <group name="frame_213">
                <mesh
                  name="Object_112"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_113" scale={0}>
              <group name="frame_212">
                <mesh
                  name="Object_115"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_115.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_116" scale={0}>
              <group name="frame_211">
                <mesh
                  name="Object_118"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_119" scale={0}>
              <group name="frame_210">
                <mesh
                  name="Object_121"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_121.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_122" scale={0}>
              <group name="frame_209">
                <mesh
                  name="Object_124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_125" scale={0}>
              <group name="frame_208">
                <mesh
                  name="Object_127"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_127.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_128" scale={0}>
              <group name="frame_207">
                <mesh
                  name="Object_130"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_131" scale={0}>
              <group name="frame_206">
                <mesh
                  name="Object_133"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_134" scale={0}>
              <group name="frame_205">
                <mesh
                  name="Object_136"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_136.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_137" scale={0}>
              <group name="frame_204">
                <mesh
                  name="Object_139"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_140" scale={0}>
              <group name="frame_203">
                <mesh
                  name="Object_142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_143" scale={0}>
              <group name="frame_202">
                <mesh
                  name="Object_145"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_145.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_146" scale={0}>
              <group name="frame_201">
                <mesh
                  name="Object_148"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_148.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_149" scale={0}>
              <group name="frame_200">
                <mesh
                  name="Object_151"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_151.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_152" scale={0}>
              <group name="frame_199">
                <mesh
                  name="Object_154"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_154.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_155" scale={0}>
              <group name="frame_198">
                <mesh
                  name="Object_157"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_157.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_158" scale={0}>
              <group name="frame_197">
                <mesh
                  name="Object_160"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_160.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_161" scale={0}>
              <group name="frame_196">
                <mesh
                  name="Object_163"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_163.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_164" scale={0}>
              <group name="frame_195">
                <mesh
                  name="Object_166"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_166.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_167" scale={0}>
              <group name="frame_194">
                <mesh
                  name="Object_169"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_169.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_170" scale={0}>
              <group name="frame_193">
                <mesh
                  name="Object_172"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_172.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_173" scale={0}>
              <group name="frame_192">
                <mesh
                  name="Object_175"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_175.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_176" scale={0}>
              <group name="frame_191">
                <mesh
                  name="Object_178"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_178.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_179" scale={0}>
              <group name="frame_190">
                <mesh
                  name="Object_181"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_181.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_182" scale={0}>
              <group name="frame_189">
                <mesh
                  name="Object_184"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_184.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_185" scale={0}>
              <group name="frame_188">
                <mesh
                  name="Object_187"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_187.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_188" scale={0}>
              <group name="frame_187">
                <mesh
                  name="Object_190"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_190.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_191" scale={0}>
              <group name="frame_186">
                <mesh
                  name="Object_193"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_193.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_194" scale={0}>
              <group name="frame_185">
                <mesh
                  name="Object_196"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_196.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_197" scale={0}>
              <group name="frame_184">
                <mesh
                  name="Object_199"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_199.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_200" scale={0}>
              <group name="frame_183">
                <mesh
                  name="Object_202"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_202.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_203" scale={0}>
              <group name="frame_182">
                <mesh
                  name="Object_205"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_205.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_206" scale={0}>
              <group name="frame_181">
                <mesh
                  name="Object_208"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_208.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_209" scale={0}>
              <group name="frame_180">
                <mesh
                  name="Object_211"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_211.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_212" scale={0}>
              <group name="frame_179">
                <mesh
                  name="Object_214"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_214.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_215" scale={0}>
              <group name="frame_178">
                <mesh
                  name="Object_217"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_217.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_218" scale={0}>
              <group name="frame_177">
                <mesh
                  name="Object_220"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_220.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_221" scale={0}>
              <group name="frame_176">
                <mesh
                  name="Object_223"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_223.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_224" scale={0}>
              <group name="frame_175">
                <mesh
                  name="Object_226"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_226.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_227" scale={0}>
              <group name="frame_174">
                <mesh
                  name="Object_229"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_229.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_230" scale={0}>
              <group name="frame_173">
                <mesh
                  name="Object_232"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_232.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_233" scale={0}>
              <group name="frame_172">
                <mesh
                  name="Object_235"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_235.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_236" scale={0}>
              <group name="frame_171">
                <mesh
                  name="Object_238"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_238.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_239" scale={0}>
              <group name="frame_170">
                <mesh
                  name="Object_241"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_241.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_242" scale={0}>
              <group name="frame_169">
                <mesh
                  name="Object_244"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_244.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_245" scale={0}>
              <group name="frame_168">
                <mesh
                  name="Object_247"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_247.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_248" scale={0}>
              <group name="frame_167">
                <mesh
                  name="Object_250"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_250.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_251" scale={0}>
              <group name="frame_166">
                <mesh
                  name="Object_253"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_253.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_254" scale={0}>
              <group name="frame_165">
                <mesh
                  name="Object_256"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_256.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_257" scale={0}>
              <group name="frame_164">
                <mesh
                  name="Object_259"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_259.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_260" scale={0}>
              <group name="frame_163">
                <mesh
                  name="Object_262"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_262.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_263" scale={0}>
              <group name="frame_162">
                <mesh
                  name="Object_265"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_265.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_266" scale={0}>
              <group name="frame_161">
                <mesh
                  name="Object_268"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_268.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_269" scale={0}>
              <group name="frame_160">
                <mesh
                  name="Object_271"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_271.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_272" scale={0}>
              <group name="frame_159">
                <mesh
                  name="Object_274"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_274.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_275" scale={0}>
              <group name="frame_158">
                <mesh
                  name="Object_277"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_277.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_278" scale={0}>
              <group name="frame_157">
                <mesh
                  name="Object_280"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_280.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_281" scale={0}>
              <group name="frame_156">
                <mesh
                  name="Object_283"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_283.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_284" scale={0}>
              <group name="frame_155">
                <mesh
                  name="Object_286"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_286.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_287" scale={0}>
              <group name="frame_154">
                <mesh
                  name="Object_289"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_289.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_290" scale={0}>
              <group name="frame_153">
                <mesh
                  name="Object_292"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_292.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_293" scale={0}>
              <group name="frame_152">
                <mesh
                  name="Object_295"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_295.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_296" scale={0}>
              <group name="frame_151">
                <mesh
                  name="Object_298"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_298.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_299" scale={0}>
              <group name="frame_150">
                <mesh
                  name="Object_301"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_301.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_302" scale={0}>
              <group name="frame_149">
                <mesh
                  name="Object_304"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_304.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_305" scale={0}>
              <group name="frame_148">
                <mesh
                  name="Object_307"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_307.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_308" scale={0}>
              <group name="frame_147">
                <mesh
                  name="Object_310"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_310.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_311" scale={0}>
              <group name="frame_146">
                <mesh
                  name="Object_313"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_313.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_314" scale={0}>
              <group name="frame_145">
                <mesh
                  name="Object_316"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_316.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_317" scale={0}>
              <group name="frame_144">
                <mesh
                  name="Object_319"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_319.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_320" scale={0}>
              <group name="frame_143">
                <mesh
                  name="Object_322"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_322.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_323" scale={0}>
              <group name="frame_142">
                <mesh
                  name="Object_325"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_325.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_326" scale={0}>
              <group name="frame_141">
                <mesh
                  name="Object_328"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_328.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_329" scale={0}>
              <group name="frame_140">
                <mesh
                  name="Object_331"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_331.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_332" scale={0}>
              <group name="frame_139">
                <mesh
                  name="Object_334"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_334.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_335" scale={0}>
              <group name="frame_138">
                <mesh
                  name="Object_337"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_337.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_338" scale={0}>
              <group name="frame_137">
                <mesh
                  name="Object_340"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_340.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_341" scale={0}>
              <group name="frame_136">
                <mesh
                  name="Object_343"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_343.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_344" scale={0}>
              <group name="frame_135">
                <mesh
                  name="Object_346"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_346.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_347" scale={0}>
              <group name="frame_134">
                <mesh
                  name="Object_349"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_349.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_350" scale={0}>
              <group name="frame_133">
                <mesh
                  name="Object_352"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_352.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_353" scale={0}>
              <group name="frame_132">
                <mesh
                  name="Object_355"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_355.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_356" scale={0}>
              <group name="frame_131">
                <mesh
                  name="Object_358"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_358.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_359" scale={0}>
              <group name="frame_130">
                <mesh
                  name="Object_361"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_361.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_362" scale={0}>
              <group name="frame_128">
                <mesh
                  name="Object_364"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_364.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_365" scale={0}>
              <group name="frame_127">
                <mesh
                  name="Object_367"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_367.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_368" scale={0}>
              <group name="frame_126">
                <mesh
                  name="Object_370"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_370.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_371" scale={0}>
              <group name="frame_125">
                <mesh
                  name="Object_373"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_373.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_374" scale={0}>
              <group name="frame_124">
                <mesh
                  name="Object_376"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_376.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_377" scale={0}>
              <group name="frame_123">
                <mesh
                  name="Object_379"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_379.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_380" scale={0}>
              <group name="frame_122">
                <mesh
                  name="Object_382"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_382.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_383" scale={0}>
              <group name="frame_121">
                <mesh
                  name="Object_385"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_385.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_386" scale={0}>
              <group name="frame_120">
                <mesh
                  name="Object_388"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_388.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_389" scale={0}>
              <group name="frame_119">
                <mesh
                  name="Object_391"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_391.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_392" scale={0}>
              <group name="frame_118">
                <mesh
                  name="Object_394"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_394.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_395" scale={0}>
              <group name="frame_117">
                <mesh
                  name="Object_397"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_397.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_398" scale={0}>
              <group name="frame_116">
                <mesh
                  name="Object_400"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_400.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_401" scale={0}>
              <group name="frame_115">
                <mesh
                  name="Object_403"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_403.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_404" scale={0}>
              <group name="frame_114">
                <mesh
                  name="Object_406"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_406.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_407" scale={0}>
              <group name="frame_113">
                <mesh
                  name="Object_409"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_409.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_410" scale={0}>
              <group name="frame_112">
                <mesh
                  name="Object_412"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_412.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_413" scale={0}>
              <group name="frame_111">
                <mesh
                  name="Object_415"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_415.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_416" scale={0}>
              <group name="frame_110">
                <mesh
                  name="Object_418"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_418.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_419" scale={0}>
              <group name="frame_109">
                <mesh
                  name="Object_421"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_421.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_422" scale={0}>
              <group name="frame_108">
                <mesh
                  name="Object_424"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_424.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_425" scale={0}>
              <group name="frame_107">
                <mesh
                  name="Object_427"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_427.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_428" scale={0}>
              <group name="frame_106">
                <mesh
                  name="Object_430"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_430.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_431" scale={0}>
              <group name="frame_105">
                <mesh
                  name="Object_433"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_433.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_434" scale={0}>
              <group name="frame_104">
                <mesh
                  name="Object_436"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_436.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_437" scale={0}>
              <group name="frame_103">
                <mesh
                  name="Object_439"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_439.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_440" scale={0}>
              <group name="frame_102">
                <mesh
                  name="Object_442"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_442.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_443" scale={0}>
              <group name="frame_101">
                <mesh
                  name="Object_445"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_445.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_446" scale={0}>
              <group name="frame_100">
                <mesh
                  name="Object_448"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_448.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_449" scale={0}>
              <group name="frame_99">
                <mesh
                  name="Object_451"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_451.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_452" scale={0}>
              <group name="frame_98">
                <mesh
                  name="Object_454"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_454.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_455" scale={0}>
              <group name="frame_97">
                <mesh
                  name="Object_457"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_457.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_458" scale={0}>
              <group name="frame_96">
                <mesh
                  name="Object_460"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_460.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_461" scale={0}>
              <group name="frame_95">
                <mesh
                  name="Object_463"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_463.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_464" scale={0}>
              <group name="frame_94">
                <mesh
                  name="Object_466"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_466.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_467" scale={0}>
              <group name="frame_93">
                <mesh
                  name="Object_469"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_469.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_470" scale={0}>
              <group name="frame_92">
                <mesh
                  name="Object_472"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_472.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_473" scale={0}>
              <group name="frame_91">
                <mesh
                  name="Object_475"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_475.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_476" scale={0}>
              <group name="frame_90">
                <mesh
                  name="Object_478"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_478.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_479" scale={0}>
              <group name="frame_89">
                <mesh
                  name="Object_481"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_481.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_482" scale={0}>
              <group name="frame_88">
                <mesh
                  name="Object_484"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_484.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_485" scale={0}>
              <group name="frame_87">
                <mesh
                  name="Object_487"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_487.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_488" scale={0}>
              <group name="frame_86">
                <mesh
                  name="Object_490"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_490.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_491" scale={0}>
              <group name="frame_85">
                <mesh
                  name="Object_493"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_493.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_494" scale={0}>
              <group name="frame_84">
                <mesh
                  name="Object_496"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_496.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_497" scale={0}>
              <group name="frame_83">
                <mesh
                  name="Object_499"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_499.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_500" scale={0}>
              <group name="frame_82">
                <mesh
                  name="Object_502"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_502.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_503" scale={0}>
              <group name="frame_81">
                <mesh
                  name="Object_505"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_505.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_506" scale={0}>
              <group name="frame_80">
                <mesh
                  name="Object_508"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_508.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_509" scale={0}>
              <group name="frame_79">
                <mesh
                  name="Object_511"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_511.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_512" scale={0}>
              <group name="frame_78">
                <mesh
                  name="Object_514"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_514.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_515" scale={0}>
              <group name="frame_77">
                <mesh
                  name="Object_517"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_517.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_518" scale={0}>
              <group name="frame_76">
                <mesh
                  name="Object_520"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_520.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_521" scale={0}>
              <group name="frame_75">
                <mesh
                  name="Object_523"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_523.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_524" scale={0}>
              <group name="frame_74">
                <mesh
                  name="Object_526"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_526.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_527" scale={0}>
              <group name="frame_73">
                <mesh
                  name="Object_529"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_529.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_530" scale={0}>
              <group name="frame_72">
                <mesh
                  name="Object_532"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_532.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_533" scale={0}>
              <group name="frame_71">
                <mesh
                  name="Object_535"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_535.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_536" scale={0}>
              <group name="frame_70">
                <mesh
                  name="Object_538"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_538.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_539" scale={0}>
              <group name="frame_69">
                <mesh
                  name="Object_541"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_541.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_542" scale={0}>
              <group name="frame_68">
                <mesh
                  name="Object_544"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_544.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_545" scale={0}>
              <group name="frame_67">
                <mesh
                  name="Object_547"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_547.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_548" scale={0}>
              <group name="frame_66">
                <mesh
                  name="Object_550"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_550.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_551" scale={0}>
              <group name="frame_65">
                <mesh
                  name="Object_553"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_553.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_554" scale={0}>
              <group name="frame_129">
                <mesh
                  name="Object_556"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_556.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_557" scale={0}>
              <group name="frame_64">
                <mesh
                  name="Object_559"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_559.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_560" scale={0}>
              <group name="frame_63">
                <mesh
                  name="Object_562"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_562.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_563" scale={0}>
              <group name="frame_62">
                <mesh
                  name="Object_565"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_565.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_566" scale={0}>
              <group name="frame_61">
                <mesh
                  name="Object_568"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_568.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_569" scale={0}>
              <group name="frame_60">
                <mesh
                  name="Object_571"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_571.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_572" scale={0}>
              <group name="frame_59">
                <mesh
                  name="Object_574"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_574.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_575" scale={0}>
              <group name="frame_58">
                <mesh
                  name="Object_577"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_577.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_578" scale={0}>
              <group name="frame_57">
                <mesh
                  name="Object_580"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_580.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_581" scale={0}>
              <group name="frame_56">
                <mesh
                  name="Object_583"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_583.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_584" scale={0}>
              <group name="frame_55">
                <mesh
                  name="Object_586"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_586.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_587" scale={0}>
              <group name="frame_54">
                <mesh
                  name="Object_589"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_589.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_590" scale={0}>
              <group name="frame_53">
                <mesh
                  name="Object_592"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_592.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_593" scale={0}>
              <group name="frame_52">
                <mesh
                  name="Object_595"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_595.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_596" scale={0}>
              <group name="frame_51">
                <mesh
                  name="Object_598"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_598.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_599" scale={0}>
              <group name="frame_50">
                <mesh
                  name="Object_601"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_601.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_602" scale={0}>
              <group name="frame_49">
                <mesh
                  name="Object_604"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_604.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_605" scale={0}>
              <group name="frame_48">
                <mesh
                  name="Object_607"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_607.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_608" scale={0}>
              <group name="frame_47">
                <mesh
                  name="Object_610"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_610.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_611" scale={0}>
              <group name="frame_46">
                <mesh
                  name="Object_613"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_613.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_614" scale={0}>
              <group name="frame_45">
                <mesh
                  name="Object_616"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_616.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_617" scale={0}>
              <group name="frame_44">
                <mesh
                  name="Object_619"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_619.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_620" scale={0}>
              <group name="frame_43">
                <mesh
                  name="Object_622"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_622.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_623" scale={0}>
              <group name="frame_42">
                <mesh
                  name="Object_625"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_625.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_626" scale={0}>
              <group name="frame_41">
                <mesh
                  name="Object_628"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_628.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_629" scale={0}>
              <group name="frame_40">
                <mesh
                  name="Object_631"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_631.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_632" scale={0}>
              <group name="frame_39">
                <mesh
                  name="Object_634"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_634.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_635" scale={0}>
              <group name="frame_38">
                <mesh
                  name="Object_637"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_637.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_638" scale={0}>
              <group name="frame_37">
                <mesh
                  name="Object_640"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_640.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_641" scale={0}>
              <group name="frame_36">
                <mesh
                  name="Object_643"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_643.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_644" scale={0}>
              <group name="frame_35">
                <mesh
                  name="Object_646"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_646.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_647" scale={0}>
              <group name="frame_34">
                <mesh
                  name="Object_649"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_649.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_650" scale={0}>
              <group name="frame_33">
                <mesh
                  name="Object_652"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_652.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_653" scale={0}>
              <group name="frame_32">
                <mesh
                  name="Object_655"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_655.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_656" scale={0}>
              <group name="frame_31">
                <mesh
                  name="Object_658"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_658.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_659" scale={0}>
              <group name="frame_30">
                <mesh
                  name="Object_661"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_661.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_662" scale={0}>
              <group name="frame_29">
                <mesh
                  name="Object_664"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_664.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_665" scale={0}>
              <group name="frame_28">
                <mesh
                  name="Object_667"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_667.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_668" scale={0}>
              <group name="frame_27">
                <mesh
                  name="Object_670"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_670.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_671" scale={0}>
              <group name="frame_26">
                <mesh
                  name="Object_673"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_673.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_674" scale={0}>
              <group name="frame_25">
                <mesh
                  name="Object_676"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_676.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_677" scale={0}>
              <group name="frame_24">
                <mesh
                  name="Object_679"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_679.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_680" scale={0}>
              <group name="frame_23">
                <mesh
                  name="Object_682"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_682.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_683" scale={0}>
              <group name="frame_22">
                <mesh
                  name="Object_685"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_685.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_686" scale={0}>
              <group name="frame_21">
                <mesh
                  name="Object_688"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_688.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_689" scale={0}>
              <group name="frame_20">
                <mesh
                  name="Object_691"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_691.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_692" scale={0}>
              <group name="frame_19">
                <mesh
                  name="Object_694"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_694.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_695" scale={0}>
              <group name="frame_18">
                <mesh
                  name="Object_697"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_697.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_698" scale={0}>
              <group name="frame_17">
                <mesh
                  name="Object_700"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_700.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_701" scale={0}>
              <group name="frame_16">
                <mesh
                  name="Object_703"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_703.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_704" scale={0}>
              <group name="frame_15">
                <mesh
                  name="Object_706"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_706.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_707" scale={0}>
              <group name="frame_14">
                <mesh
                  name="Object_709"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_709.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_710" scale={0}>
              <group name="frame_13">
                <mesh
                  name="Object_712"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_712.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_713" scale={0}>
              <group name="frame_12">
                <mesh
                  name="Object_715"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_715.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_716" scale={0}>
              <group name="frame_11">
                <mesh
                  name="Object_718"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_718.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_719" scale={0}>
              <group name="frame_10">
                <mesh
                  name="Object_721"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_721.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_722" scale={0}>
              <group name="frame_9">
                <mesh
                  name="Object_724"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_724.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_725" scale={0}>
              <group name="frame_8">
                <mesh
                  name="Object_727"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_727.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_728" scale={0}>
              <group name="frame_7">
                <mesh
                  name="Object_730"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_730.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_731" scale={0}>
              <group name="frame_6">
                <mesh
                  name="Object_733"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_733.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_734" scale={0}>
              <group name="frame_5">
                <mesh
                  name="Object_736"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_736.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_737" scale={0}>
              <group name="frame_4">
                <mesh
                  name="Object_739"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_739.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_740" scale={0}>
              <group name="frame_3">
                <mesh
                  name="Object_742"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_742.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_743" scale={0}>
              <group name="frame_2">
                <mesh
                  name="Object_745"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_745.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_746" scale={0}>
              <group name="frame_1">
                <mesh
                  name="Object_748"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_748.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
            <group name="Object_749">
              <group name="frame_0">
                <mesh
                  name="Object_751"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_751.geometry}
                  material={materials["Material.001"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/ocean_wave_sim.glb");
